doctrine:
    dbal:
        connections:
            myproject:
                driver: 'pdo_mysql'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                override_url: true
                url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            myproject:
                connection: myproject
                mappings:
                    MyProject:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/MyProject'
                        prefix: 'App\Entity\MyProject'
                        alias: MyProject
